### Listar
GET  http://localhost:8002/api/movies

### Filtrar por género
GET  http://localhost:8002/api/movies?genre=Drama

### Crear
POST http://localhost:8002/api/addMovie
Content-Type: application/json

{
  "title": "S",
  "year": 2015,
  "director": "Sai",
  "duration": 33,
  "poster": "https://example.com/spiderman.jpg",
  "rate": 5.3
}

### Actualizar (parcial o total)
PUT http://localhost:8002/api/updateMovie/f06b1f37-7e07-11f0-9857-b0a1178f8903
Content-Type: application/json

{
  "title": "Spider Reborn",
    "year": 2015,
  "director": "Sai",
  "duration": 33,
  "poster": "https://example.com/spiderman.jpg",
  "rate": 7.9
}

### Eliminar
DELETE http://localhost:8002/api/deleteMovie/b48c81d2-7e07-11f0-9857-b0a1178f8903
