GET  http://localhost:8001/api/

###
GET  http://localhost:8001/api/movies?genre=Drama

###
POST http://localhost:8001/api/addMovie
Content-Type: application/json

{
  "title": "S",
  "year": 2015,
  "director": "Sai",
  "duration": 33,
  "poster": "https://example.com/spiderman.jpg",
  "rate": 5.3
}

###
PUT http://localhost:8001/api/updateMovie/62787913-7e01-11f0-9857-b0a1178f8903
 Content-Type: application/json

{
  "title": "S",
  "year": 2015,
  "director": "Sai",
  "duration": 33,
  "poster": "https://example.com/spiderman.jpg",
  "rate": 5.3
}